#!/usr/bin/env bash
#

source ./repo-functions.sh

PSYS="${HOME}/Repos/system"
mkdir -p "${PSYS}"
mkdir -p "${HOME}/.dots/bin"
mkdir -p "${HOME}/.config/emacs/pkgs"

if [[ -x "${PSYS}/ledger/acprep" ]]; then
    echo "Found local ledger repository..."
    cde "${PSYS}/ledger"
    ./acprep opt update
else
    get_or_update "${PSYS}"/ledger ledger/ledger master
    if (( UPDATED > 0 )); then
        cde "${PSYS}/ledger"
        ./acprep opt update
    fi
fi

DEST="${HOME}/.dots/bin/ledger"
if [[ -x "${PSYS}/ledger/ledger" ]]; then
    [[ -L "${DEST}" ]] && rm "${DEST}"
    ln -sn "${PSYS}/ledger/ledger" "${DEST}"
else
    echo "Installation failed... ledger cannot be added to path" >&2
    exit 1
fi

get_or_update "${PSYS}"/ledger-mode ledger/ledger-mode master
if (( UPDATED > 0 )); then
    cde "${PSYS}/ledger-mode"
    mkdir build
    cp ./*.el build
    emacs -batch --eval '(package-initialize)' -f batch-byte-compile ./build/*.el
    mv ./build "${HOME}/.config/emacs/pkgs/ledger"
fi
