#!/usr/bin/env bash
#
# Install code linters and lsp

command -v pipx > /dev/null ||
    { echo "pipx must be installed and added to path" >&2; exit 1; }

source ./repo-functions.sh

if command -v ruff /dev/null; then
    pipx upgrade ruff
else
    pipx install ruff
fi

if command -v pylsp /dev/null; then
    pipx upgrade python-lsp-server
else
    pipx install "python-lsp-server[all]";
    pipx inject python-lsp-server python-lsp-black;
    pipx inject python-lsp-server pyls-isort;
    pipx inject python-lsp-server pylsp-mypy;
fi

mkdir -p "${HOME}/.dots/bin"

system_info

get_github_asset valentjn/ltex-ls "${SYS}"
if [[ -n "${RET}" ]]; then
    echo "Expanding file"
    DEST="${HOME}"/Repos/system/
    RBIN=$(tar xzvf "${RET}" -C "${DEST}" | grep "ltex-ls$")
    if [[ -n "${RBIN}" ]]; then
        FBIN="${DEST}${RBIN#./}"
        ln -sn "${FBIN}" "${HOME}"/.dots/bin/ltex-ls
        ln -sn "${FBIN%-ls}-cli" "${HOME}"/.dots/bin/ltex-cli
        rm "${RET}"
    else
        echo "Unable to detect ltex executable." >&2
        echo "ltex was not added to the path." >&2
    fi
fi

get_github_asset koalaman/shellcheck "${SYS}.${ARCH}"
if [[ -n "${RET}" ]]; then
    echo "Expanding file"
    DEST="${HOME}"/Repos/system/
    RBIN=$(tar xvf "${RET}" -C "${DEST}" | grep "shellcheck$")
    if [[ -n "${RBIN}" ]]; then
        FBIN="${DEST}${RBIN#./}"
        mv "${FBIN}" "${HOME}"/.dots/bin/
        rm "${RET}"
    else
        echo "Unable to detect shellcheck executable." >&2
        echo "shellcheck was not added to the path." >&2
    fi
fi
