#!/usr/bin/env bash
#
# Setup configuration


cd "${HOME}" || { echo "Unable to enter home directory." >&2; exit 1; }

BRANCH="${1:-main}"
git clone --branch "${BRANCH}" --bare https://github.com/foxfriday/dots.git "${HOME}/.dots.git"

mapfile -t FILES < <(git --git-dir="$HOME/.dots.git/" --work-tree="$HOME" ls-tree -r --name-only "${BRANCH}" | sort)

for FILE in "${FILES[@]}"; do
    if [[ -f "${FILE}" ]]; then
        DIR="${FILE%/*}"
        if [[ -d ".dots_backup/${DIR}" ]]; then
            mv "${FILE}" ".dots_backup/${FILE}"
        else
            mkdir -p ".dots_backup/${DIR}"
            mv "${FILE}" ".dots_backup/${FILE}"
        fi
    fi
done

git --git-dir="$HOME/.dots.git/" --work-tree="$HOME" checkout "${BRANCH}"
git --git-dir="$HOME/.dots.git/" --work-tree="$HOME" config --local status.showUntrackedFiles no
